In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import joblib
from sklearn.metrics import roc_curve

# --- 1. The Academic MLP Architecture ---
# We use a very lightweight architecture (64 -> 32 -> 1) because the input 
# only consists of 14 biological features. A larger network would simply 
# memorize the training data (overfit) rather than learning generalizable patterns.
class BioAcademicMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            # First hidden layer: 64 neurons with Batch Normalization for mathematical stability
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3), # Dropout randomly disables 30% of neurons to force the model to generalize

            # Second hidden layer compresses the features down to 32 neurons
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.3),

            # Final output layer compresses down to exactly 1 number (probability of real vs. fake)
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)

# --- 2. Function to Calculate EER ---
# Equal Error Rate (EER) is the standard benchmark metric for deepfake detection. 
# It finds the exact threshold where the False Acceptance Rate matches the False Rejection Rate.
def calculate_eer(y_true, y_scores):
    fpr, tpr, _ = roc_curve(y_true, y_scores, pos_label=1)
    fnr = 1 - tpr
    # Find the index where the difference between False Positive Rate and False Negative Rate is the absolute smallest
    idx = np.nanargmin(np.abs(fpr - fnr))
    eer = (fpr[idx] + fnr[idx]) / 2.0
    return eer * 100

# --- 3. Feature Prep (Must perfectly match training) ---
# This function applies the exact same data engineering used during the training phase 
# to ensure the neural network receives the evaluation data in the precise format it expects.
def prepare_features(df):
    df = df.copy()
    
    # Safety cleanup: If Praat failed mathematically (e.g., divided by zero), it might output infinity.
    # We replace infinity with NaN and drop those rows to prevent the neural network from crashing.
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    # Feature engineering: We create a new "Coefficient of Variation" feature for pitch.
    # The 1e-6 is a tiny mathematical safety net added to the denominator to prevent division by exactly zero.
    if "meanF0" in df.columns and "stdevF0" in df.columns:
        df["f0_cov"] = df["stdevF0"] / (df["meanF0"] + 1e-6)

    # Log transforms: Jitter and Shimmer values are extremely small but can spike drastically.
    # Applying a natural logarithm flattens these massive spikes, making the data smoother for the AI.
    jsh_cols = [
        "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
        "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
    ]
    for col in jsh_cols:
        if col in df.columns:
            # np.clip forces any number smaller than 1e-6 to become exactly 1e-6 
            # because you mathematically cannot take the logarithm of zero or a negative number.
            df[col] = np.log(np.clip(df[col].astype(float), 1e-6, None))

    # Reorder columns to strictly match the exact sequence the model was trained on
    feature_cols = ["meanF0", "f0_cov", "hnr"] + jsh_cols
    
    # Convert Pandas DataFrames into raw numpy arrays for PyTorch
    X = df[feature_cols].values.astype(np.float32)
    y = df["label"].values.astype(np.float32)
    
    return X, y


def main():
    # 1. Load the Scaler
    print("Loading scaler from training phase...")
    # CRITICAL: We MUST use the scaler fitted on the training data. If we recalculated a new scaler 
    # based on the evaluation data, the distributions would shift, and the model would be completely blind.
    scaler = joblib.load(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_scaler.pkl")

    # 2. Load the Model
    input_dim = 14 # 14 biological features (Pitch, HNR, Jitter, Shimmer)
    model = BioAcademicMLP(input_dim)
    # Load the saved mathematical weights from our best performing training epoch
    model.load_state_dict(torch.load(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_mlp_weights.pt"))
    # .eval() disables training features like Dropout, safely locking the model into inference mode
    model.eval()
    
    # 3. Load the Evaluation Data
    print("Loading evaluation dataset (this may take a moment)...")
    # This CSV contains the features extracted from the 600,000+ file evaluation dataset
    eval_df = pd.read_csv(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_bio_academic.csv")
    
    # Separate into Clean (nocodec) and Compressed
    # This split is how we benchmark the system's robustness against real-world data degradation (like MP3/M4A compression)
    clean_df = eval_df[eval_df['codec'] == 'nocodec']
    compressed_df = eval_df[eval_df['codec'] != 'nocodec']
    
    datasets = {"Clean (No Codec)": clean_df, "Compressed": compressed_df}
    
    for condition, df in datasets.items():
        if len(df) == 0:
            print(f"\n--- Condition: {condition} Audio ---")
            print("No files found for this condition.")
            continue
            
        # Prep features (calculate f0_cov, execute log transforms, drop NaNs)
        X_eval, y_eval = prepare_features(df)
        
        # Apply the training scaler to normalize the evaluation features (using .transform, NOT .fit_transform)
        X_eval_scaled = scaler.transform(X_eval)
        X_tensor = torch.tensor(X_eval_scaled, dtype=torch.float32)
        
        # 4. Batched Inference (To prevent RAM exhaustion)
        # Even though these are just arrays of 14 numbers, attempting to pass hundreds of thousands 
        # of rows through the neural network simultaneously will exhaust the memory. We chunk it.
        batch_size = 5000
        all_scores = []
        
        # torch.no_grad() prevents PyTorch from tracking memory-heavy gradients since we are not training
        with torch.no_grad():
            for i in range(0, len(X_tensor), batch_size):
                # Slice the massive tensor into smaller, digestible batches
                batch = X_tensor[i:i+batch_size]
                logits = model(batch)
                
                # Sigmoid squashes the raw model output into a clean percentage probability (0.0 to 1.0)
                scores = torch.sigmoid(logits).numpy().flatten()
                all_scores.extend(scores)
                
        # Calculate and print the final EER for this specific degradation condition
        eer = calculate_eer(y_eval, all_scores)
        print(f"\n--- Condition: {condition} Audio ---")
        print(f"Files tested: {len(X_eval)}")  # using X_eval len because some files might have been dropped during cleaning
        print(f"Equal Error Rate (EER): {eer:.2f}%")


if __name__ == "__main__":
    main()

Loading scaler from training phase...
Loading evaluation dataset (this may take a moment)...

--- Condition: Clean (No Codec) Audio ---
Files tested: 39132
Equal Error Rate (EER): 28.91%

--- Condition: Compressed Audio ---
Files tested: 312778
Equal Error Rate (EER): 29.64%

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import joblib
from sklearn.metrics import roc_curve


# -------- 1. Re-declare the Lightweight MLP Architecture --------
# This model definition must match the architecture used during training.
# When loading saved weights, PyTorch needs the exact same layer structure.
class SSLMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # nn.Sequential lets us define the full feed-forward network layer by layer.
        # Input: SSL embedding vector extracted earlier from Wav2Vec2 features.
        # Output: a single logit for binary classification (real vs fake).
        self.network = nn.Sequential(
            # First fully connected layer:
            # maps the input SSL feature vector into a 256-dimensional hidden space.
            nn.Linear(input_dim, 256),

            # ReLU adds non-linearity so the model can learn more complex patterns.
            nn.ReLU(),

            # BatchNorm stabilizes activations across a batch and helps training/evaluation consistency.
            nn.BatchNorm1d(256),

            # Dropout was used during training to reduce overfitting.
            # In eval() mode below, dropout is automatically disabled.
            nn.Dropout(0.3),

            # Second hidden layer: compresses 256 features down to 128.
            nn.Linear(256, 128),
            nn.ReLU(),

            # Another dropout layer for regularization.
            nn.Dropout(0.3),

            # Final output layer:
            # produces one raw score (logit) for binary classification.
            # This is not yet a probability; sigmoid is applied later.
            nn.Linear(128, 1)
        )

    def forward(self, x):
        # Standard forward pass through the network.
        return self.network(x)



# -------- 2. EER Calculation Function --------
def calculate_eer(y_true, y_scores):
    """
    Calculates Equal Error Rate (EER) using the ROC curve.

    y_true   : ground-truth labels (1 = bonafide, 0 = spoof)
    y_scores : model output scores after sigmoid, treated as confidence values

    EER is the point where:
    - False Positive Rate (FPR)
    - False Rejection Rate (FRR = 1 - TPR)
    are closest to each other.

    Lower EER means better performance.
    """
    # roc_curve gives FPR, TPR, and thresholds across many decision boundaries.
    fpr, tpr, thresholds = roc_curve(y_true, y_scores, pos_label=1)

    # False Rejection Rate is the complement of True Positive Rate.
    frr = 1 - tpr

    # Find the point where FPR and FRR are closest.
    eer = fpr[np.nanargmin(np.absolute(fpr - frr))]

    # Return EER as a percentage instead of a fraction.
    return eer * 100



# -------- 3. Main Evaluation --------
def main():
    print("Loading evaluation data (this might take a moment)...")

    # Load the large evaluation CSV generated earlier from SSL feature extraction.
    # Each row corresponds to one audio file.
    # This file is expected to already contain:
    # - filename
    # - codec
    # - label
    # - ssl_0, ssl_1, ssl_2, ...
    eval_df = pd.read_csv(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_ssl_features.csv")
    
    # Identify all SSL feature columns dynamically.
    # This avoids hardcoding feature count and makes the script flexible
    # as long as all SSL columns follow the naming pattern ssl_*.
    feature_cols = [c for c in eval_df.columns if c.startswith("ssl_")]
    input_dim = len(feature_cols)
    
    # 1. Load the scaler fitted on the training data.
    # This is important because evaluation features must be transformed
    # using the exact same scaling statistics as training features.
    print("Loading StandardScaler from training phase...")
    try:
        scaler = joblib.load(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_scaler.pkl")
    except FileNotFoundError:
        print("ERROR: Cannot find 'ssl_scaler.pkl'. Please ensure it is in the specified directory.")
        return


    # 2. Load the trained model weights.
    # First create a fresh model instance with the correct input dimension,
    # then load the saved parameters into it.
    print(f"Loading trained model with input dimension {input_dim}...")
    model = SSLMLP(input_dim)
    try:
        model.load_state_dict(torch.load(r"C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_mlp_weights.pt"))
    except FileNotFoundError:
        print("ERROR: Cannot find 'ssl_mlp_weights.pt'. Please ensure it is in the specified directory.")
        return
         
    # Switch the model to evaluation mode.
    # This disables training-specific behavior such as dropout randomness.
    model.eval()
    
    # 3. Separate the evaluation set into two conditions:
    # - Clean audio: codec == "nocodec"
    # - Compressed/degraded audio: everything else
    #
    # This lets us measure how well the model handles clean data
    # versus real-world codec degradation.
    clean_df = eval_df[eval_df['codec'] == 'nocodec']
    compressed_df = eval_df[eval_df['codec'] != 'nocodec']
    
    datasets = {"Clean (No Codec)": clean_df, "Compressed": compressed_df}
    
    # Evaluate each condition independently.
    for condition, df in datasets.items():
        if len(df) == 0:
            print(f"\n--- Condition: {condition} Audio ---")
            print("No files found for this condition.")
            continue
            
        # Extract the model input matrix from the SSL feature columns.
        X_eval = df[feature_cols].values

        # Extract the true labels for EER calculation later.
        y_eval = df['label'].values
        
        # Scale the features using the training-phase scaler.
        # We use transform(), not fit_transform(), because we are applying
        # previously learned normalization rather than recomputing it.
        X_eval_scaled = scaler.transform(X_eval)
        
        # Convert scaled NumPy array into a PyTorch tensor so the model can process it.
        X_tensor = torch.tensor(X_eval_scaled, dtype=torch.float32)
        
        # 4. Get predictions
        # We do inference in manual batches to avoid holding the entire
        # evaluation matrix inside the forward pass at once.
        # This is especially useful when the evaluation set is very large.
        batch_size = 5000
        all_scores = []
        
        # Disable gradient tracking during inference.
        # This reduces memory usage and speeds up evaluation because
        # we are not updating model weights here.
        with torch.no_grad():
            for i in range(0, len(X_tensor), batch_size):
                # Slice a chunk of rows for the current batch.
                batch = X_tensor[i:i+batch_size]

                # Forward pass through the model.
                # Output shape will be [batch_size, 1] as logits.
                logits = model(batch)

                # Convert logits into probabilities in the range [0, 1].
                # Higher score means the model is more confident the sample is bonafide.
                scores = torch.sigmoid(logits).numpy().flatten()

                # Collect scores from all batches into one list.
                all_scores.extend(scores)
                
        # Convert final prediction list into a NumPy array for metric computation.
        all_scores = np.array(all_scores)
        
        # Calculate and print Equal Error Rate for the current condition.
        eer = calculate_eer(y_eval, all_scores)
        print(f"\n--- Condition: {condition} Audio ---")
        print(f"Files tested: {len(df)}")
        print(f"Equal Error Rate (EER): {eer:.2f}%")



if __name__ == "__main__":
    # Entry point of the script.
    # Runs the full evaluation pipeline when the file is executed directly.
    main()

Loading evaluation data (this might take a moment)...
Loading StandardScaler from training phase...
Loading trained model with input dimension 1536...

--- Condition: Clean (No Codec) Audio ---
Files tested: 44772
Equal Error Rate (EER): 18.75%

--- Condition: Compressed Audio ---
Files tested: 357161
Equal Error Rate (EER): 20.54%

In [ ]:
import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import joblib
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_curve
from tqdm import tqdm



# --- 1. Paths ---
# Use a fixed absolute project path so all model/scaler/data files are loaded
# from a known location on disk.
# This avoids issues that sometimes happen with dynamic relative paths.
BASE_DIR = r"C:\Users\adith\Desktop\Projects\Audio Deepfake"

# Path to the scaler fitted during fusion model training.
# This scaler contains the exact mean/std statistics used to normalize features.
SCALER_PATH = os.path.join(BASE_DIR, "fusion_academic_scaler.pkl")

# Path to the trained fusion model weights.
# These weights represent the learned parameters of the final classifier.
WEIGHTS_PATH = os.path.join(BASE_DIR, "fusion_academic_mlp_weights.pt")

# CSV containing SSL / Wav2Vec2-based features extracted for the evaluation set.
SSL_CSV = os.path.join(BASE_DIR, "eval_df_ssl_features.csv")

# CSV containing biological / signal-level voice features for the same evaluation set.
BIO_CSV = os.path.join(BASE_DIR, "eval_df_bio_academic.csv")



# --- 2. Architecture ---
# FusionMLP is the final classifier that consumes both:
# 1) SSL embeddings (high-level learned speech representation)
# 2) Biological features (pitch/jitter/shimmer/HNR-derived features)
#
# The network gradually compresses the feature space:
# 1550 -> 512 -> 128 -> 32 -> 1
#
# Final output is a single logit:
# - higher value -> more likely bonafide / real
# - lower value -> more likely spoof / fake
class FusionMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # nn.Sequential lets us define the whole feed-forward stack in order.
        self.network = nn.Sequential(
            # First layer:
            # takes the full fused feature vector and expands/compresses it
            # into 512 learned hidden units.
            nn.Linear(input_dim, 512),

            # ReLU introduces non-linearity so the model can learn complex patterns,
            # not just straight linear boundaries.
            nn.ReLU(),

            # BatchNorm stabilizes training and helps keep activations in a healthy range.
            nn.BatchNorm1d(512),

            # Dropout randomly turns off some neurons during training to reduce overfitting.
            nn.Dropout(0.4),

            # Second hidden block
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),

            # Third hidden block
            nn.Linear(128, 32),
            nn.ReLU(),
            nn.Dropout(0.3),

            # Final output layer:
            # one value only, because this is binary classification.
            nn.Linear(32, 1)
        )

    def forward(self, x):
        # Standard forward pass:
        # input features -> stacked neural layers -> output logit
        return self.network(x)



def calculate_eer(y_true, y_scores):
    # EER = Equal Error Rate.
    # This is a common metric in verification / spoof detection tasks.
    #
    # y_true   : ground-truth labels (0 = spoof, 1 = bonafide)
    # y_scores : continuous prediction scores/probabilities
    #
    # roc_curve gives:
    # fpr = false positive rate
    # tpr = true positive rate
    # thresholds = score cutoffs used to compute the curve
    fpr, tpr, _ = roc_curve(y_true, y_scores, pos_label=1)

    # False negative rate is the opposite of true positive rate.
    fnr = 1 - tpr

    # Find the point where FPR and FNR are closest.
    # That operating point is used as the EER estimate.
    idx = np.nanargmin(np.abs(fpr - fnr))

    # A slightly smoother estimate is used here:
    # average of FPR and FNR at the closest point, then convert to percentage.
    return ((fpr[idx] + fnr[idx]) / 2.0) * 100



# --- 3. RAM-Safe PyTorch Dataset ---
# This Dataset is designed for large-scale evaluation.
#
# Key idea:
# Instead of converting the entire evaluation dataframe into one huge NumPy array
# and scaling everything at once (which can consume a lot of RAM),
# this class loads and scales only one row at a time when DataLoader asks for it.
class DFEvalDataset(Dataset):
    def __init__(self, dataframe, scaler, feature_cols):
        # Keep only references here.
        # We do NOT call .values over the entire dataframe because that would
        # materialize a very large dense matrix in memory.
        self.df = dataframe
        self.scaler = scaler
        self.feature_cols = feature_cols


    def __len__(self):
        # Required by PyTorch Dataset.
        # Returns number of samples available.
        return len(self.df)


    def __getitem__(self, idx):
        # Pull only one row from the dataframe for this exact sample.
        row = self.df.iloc[idx]

        # Extract only the model feature columns for this row.
        # .reshape(1, -1) is needed because sklearn scalers expect 2D input:
        # shape = [num_samples, num_features]
        features = row[self.feature_cols].values.astype(np.float32).reshape(1, -1)
        
        # Scale this single row using the scaler fitted during training.
        # This guarantees evaluation data is normalized in exactly the same way
        # as the training data.
        scaled_features = self.scaler.transform(features).flatten()

        # Extract label for evaluation.
        label = np.float32(row["label"])
        
        # Return PyTorch tensors so DataLoader can batch them efficiently.
        return torch.tensor(scaled_features), torch.tensor(label)



def main():
    print("Loading Fusion Scaler...")

    # Load the fitted scaler.
    # If the file is missing, stop immediately with a clear message.
    try:
        scaler = joblib.load(SCALER_PATH)
    except FileNotFoundError:
        print(f"ERROR: Could not find scaler at {SCALER_PATH}")
        return


    # 1550 input features =
    # 1536 SSL features + 14 biological features
    model = FusionMLP(1550)

    # Load trained model weights into the architecture.
    # If the weights file is missing, stop cleanly.
    try:
        model.load_state_dict(torch.load(WEIGHTS_PATH))
    except FileNotFoundError:
        print(f"ERROR: Could not find model weights at {WEIGHTS_PATH}")
        return
        
    # Set model to evaluation mode.
    # This disables training-time behavior such as dropout randomness
    # and uses stored BatchNorm statistics.
    model.eval()
    
    print("Loading SSL and Bio Evaluation datasets...")

    # Read the SSL feature CSV.
    # This contains filename, codec, label, and ssl_* columns.
    ssl_df = pd.read_csv(SSL_CSV)

    # Read the biological feature CSV.
    # We drop label and codec here because those columns already exist in ssl_df,
    # and we only want one copy of them after merging.
    bio_df = pd.read_csv(BIO_CSV).drop(columns=["label", "codec"])
    
    print("Fusing evaluation datasets...")

    # Merge both feature sources by filename.
    # how="inner" means:
    # keep only files that successfully exist in BOTH datasets.
    #
    # This is important because if one branch failed to process a file,
    # we should not evaluate that file with partial features.
    eval_df = pd.merge(ssl_df, bio_df, on="filename", how="inner")
    
    # These raw dataframes are no longer needed after merge.
    # Delete them explicitly to release memory as early as possible.
    del ssl_df
    del bio_df
    
    print("Applying feature engineering...")

    # Replace any +inf / -inf values with NaN.
    # This protects downstream math from exploding.
    eval_df.replace([np.inf, -np.inf], np.nan, inplace=True)

    # Drop rows with missing values after replacement.
    # This ensures only valid rows continue into evaluation.
    eval_df.dropna(inplace=True)

    # Create f0_cov = coefficient of variation for pitch.
    # This describes pitch variability relative to average pitch.
    #
    # +1e-6 is a small safety term to avoid divide-by-zero.
    eval_df["f0_cov"] = eval_df["stdevF0"] / (eval_df["meanF0"] + 1e-6)
    
    # These are the jitter and shimmer related columns.
    # Their raw value ranges are usually skewed and very small,
    # so log-transforming them helps compress large outliers and stabilize scale.
    jsh_cols = ["j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp", "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"]

    for col in jsh_cols:
        if col in eval_df.columns:
            # np.clip(..., 1e-6, None) ensures no value goes below 1e-6.
            # This prevents log(0) and log of negative values.
            eval_df[col] = np.log(np.clip(eval_df[col].astype(float), 1e-6, None))


    # Collect all SSL columns dynamically.
    # This is safer than hardcoding ssl_0 ... ssl_1535 manually.
    ssl_cols = [c for c in eval_df.columns if c.startswith("ssl_")]

    # Final feature order fed into the fusion model.
    # Order matters because the scaler and model were trained using a fixed feature layout.
    feature_cols = ssl_cols + ["meanF0", "f0_cov", "hnr"] + jsh_cols
    
    # Split evaluation into two conditions:
    # 1) Clean audio = no codec degradation
    # 2) Compressed audio = codec-applied / degraded audio
    #
    # This helps compare robustness under clean vs real-world degraded conditions.
    datasets = {
        "Clean (No Codec)": eval_df[eval_df['codec'] == 'nocodec'],
        "Compressed": eval_df[eval_df['codec'] != 'nocodec']
    }
    
    for condition, df in datasets.items():
        # Skip empty groups safely.
        if len(df) == 0:
            continue
            
        print(f"\nEvaluating {condition} Audio ({len(df)} files)...")
        
        # Create a memory-safe dataset object.
        # Each sample is loaded/scaled row-by-row rather than all at once.
        dataset = DFEvalDataset(df, scaler, feature_cols)

        # DataLoader batches samples for efficient inference.
        # batch_size=2048 gives faster throughput while remaining manageable in memory.
        # shuffle=False because evaluation must be deterministic and order does not matter.
        # num_workers=0 keeps loading in the main process, which is simple and stable.
        loader = DataLoader(dataset, batch_size=2048, shuffle=False, num_workers=0)
         
        # These lists store model outputs and ground-truth labels across the full split.
        all_scores, all_labels = [], []
        
        # Disable gradient tracking:
        # saves memory and speeds up inference because we are not updating weights.
        with torch.no_grad():
            for batch_features, batch_labels in tqdm(loader, desc="Inference"):
                # Forward pass through fusion model.
                logits = model(batch_features)

                # Convert raw logits to probabilities in [0, 1].
                scores = torch.sigmoid(logits).numpy().flatten()
                
                # Accumulate predictions and true labels for final EER calculation.
                all_scores.extend(scores)
                all_labels.extend(batch_labels.numpy())
                
        # Compute Equal Error Rate over the full split.
        eer = calculate_eer(all_labels, all_scores)
        print(f"Equal Error Rate (EER): {eer:.2f}%")



if __name__ == "__main__":
    # Standard Python entry point.
    # Ensures main() runs only when this file is executed directly.
    main()

Loading Fusion Scaler...
Loading SSL and Bio Evaluation datasets...
Fusing evaluation datasets...
Applying feature engineering...

Evaluating Clean (No Codec) Audio (44771 files)...

Inference: 100%|██████████| 22/22 [03:01<00:00,  8.25s/it]

Equal Error Rate (EER): 18.41%

Evaluating Compressed Audio (357150 files)...

Inference: 100%|██████████| 175/175 [24:51<00:00,  8.52s/it]

Equal Error Rate (EER): 20.25%

In [ ]:
import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import joblib
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_curve
from tqdm import tqdm

# ==========================================
# 1. FILE PATHS (UPDATE THESE IF NEEDED)
# ==========================================
BASE_DIR = r"C:\Users\adith\Desktop\Projects\Audio Deepfake"

# Data
SSL_CSV = os.path.join(BASE_DIR, "eval_df_ssl_features.csv")
BIO_CSV = os.path.join(BASE_DIR, "eval_df_bio_academic.csv")

# SSL Standalone Model
SSL_SCALER_PATH = os.path.join(BASE_DIR, "ssl_scaler.pkl")
SSL_WEIGHTS_PATH = os.path.join(BASE_DIR, "ssl_mlp_weights.pt")

# Bio Standalone Model
BIO_SCALER_PATH = os.path.join(BASE_DIR, "bio_academic_scaler.pkl")
BIO_WEIGHTS_PATH = os.path.join(BASE_DIR, "bio_academic_mlp_weights.pt")

# ==========================================
# 2. NEURAL NETWORK ARCHITECTURES
# ==========================================
class SSLModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 256),         # network.0
            nn.ReLU(),                         # network.1
            nn.BatchNorm1d(256),               # network.2
            nn.Dropout(0.4),                   # network.3
            nn.Linear(256, 128),               # network.4
            nn.ReLU(),                         # network.5
            nn.Dropout(0.3),                   # network.6 (No BatchNorm here!)
            nn.Linear(128, 1)                  # network.7
        )
    def forward(self, x):
        return self.network(x)

class BioModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),          # network.0
            nn.ReLU(),                         # network.1
            nn.BatchNorm1d(64),                # network.2
            nn.Dropout(0.4),                   # network.3
            nn.Linear(64, 32),                 # network.4
            nn.ReLU(),                         # network.5
            nn.Dropout(0.3),                   # network.6
            nn.Linear(32, 1)                   # network.7
        )
    def forward(self, x):
        return self.network(x)
    
def calculate_eer(y_true, y_scores):
    fpr, tpr, _ = roc_curve(y_true, y_scores, pos_label=1)
    fnr = 1 - tpr
    idx = np.nanargmin(np.abs(fpr - fnr))
    return ((fpr[idx] + fnr[idx]) / 2.0) * 100

# ==========================================
# 3. RAM-SAFE MULTI-MODEL DATASET
# ==========================================
class MultiModelEvalDataset(Dataset):
    def __init__(self, dataframe, ssl_scaler, bio_scaler, ssl_cols, bio_cols):
        self.df = dataframe
        self.ssl_scaler = ssl_scaler
        self.bio_scaler = bio_scaler
        self.ssl_cols = ssl_cols
        self.bio_cols = bio_cols

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        # Extract and scale SSL features for this row
        ssl_features = row[self.ssl_cols].values.astype(np.float32).reshape(1, -1)
        ssl_scaled = self.ssl_scaler.transform(ssl_features).flatten()
        
        # Extract and scale Bio features for this row
        bio_features = row[self.bio_cols].values.astype(np.float32).reshape(1, -1)
        bio_scaled = self.bio_scaler.transform(bio_features).flatten()
        
        label = np.float32(row["label"])
        
        return torch.tensor(ssl_scaled), torch.tensor(bio_scaled), torch.tensor(label)

def main():
    print("Loading Scalers...")
    ssl_scaler = joblib.load(SSL_SCALER_PATH)
    bio_scaler = joblib.load(BIO_SCALER_PATH)

    print("Loading Models...")
    # Initialize networks based on the number of features they were trained on
    ssl_model = SSLModel(input_dim=1536)
    ssl_model.load_state_dict(torch.load(SSL_WEIGHTS_PATH))
    ssl_model.eval()

    bio_model = BioModel(input_dim=14)
    bio_model.load_state_dict(torch.load(BIO_WEIGHTS_PATH))
    bio_model.eval()
    
    print("Loading Evaluation datasets...")
    ssl_df = pd.read_csv(SSL_CSV)
    bio_df = pd.read_csv(BIO_CSV).drop(columns=["label", "codec"])
    
    print("Merging datasets to ensure perfect alignment...")
    eval_df = pd.merge(ssl_df, bio_df, on="filename", how="inner")
    
    # Free up RAM immediately
    del ssl_df
    del bio_df
    
    print("Applying Biological feature engineering...")
    eval_df.replace([np.inf, -np.inf], np.nan, inplace=True)
    eval_df.dropna(inplace=True)
    eval_df["f0_cov"] = eval_df["stdevF0"] / (eval_df["meanF0"] + 1e-6)
    
    jsh_cols = ["j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp", "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"]
    for col in jsh_cols:
        eval_df[col] = np.log(np.clip(eval_df[col].astype(float), 1e-6, None))

    # Identify exact columns for each model
    ssl_cols = [c for c in eval_df.columns if c.startswith("ssl_")]
    bio_cols = ["meanF0", "f0_cov", "hnr"] + jsh_cols
    
    datasets = {
        "Clean (No Codec) Audio": eval_df[eval_df['codec'] == 'nocodec'],
        "Compressed Audio": eval_df[eval_df['codec'] != 'nocodec']
    }
    
    for condition, df in datasets.items():
        if len(df) == 0: continue
            
        print(f"\n========================================")
        print(f"Evaluating {condition} ({len(df)} files)")
        print(f"========================================")
        
        dataset = MultiModelEvalDataset(df, ssl_scaler, bio_scaler, ssl_cols, bio_cols)
        # num_workers=0 bypasses the Windows multiprocessing crash
        loader = DataLoader(dataset, batch_size=2048, shuffle=False, num_workers=0)
        
        all_ssl_scores, all_bio_scores, all_labels = [], [], []
        
        print("Running simultaneous inference...")
        with torch.no_grad():
            for batch_ssl, batch_bio, batch_labels in tqdm(loader, desc="Inference"):
                # Run both models
                ssl_logits = ssl_model(batch_ssl)
                bio_logits = bio_model(batch_bio)
                
                # Convert logits to 0-1 percentage scores using Sigmoid
                ssl_scores = torch.sigmoid(ssl_logits).numpy().flatten()
                bio_scores = torch.sigmoid(bio_logits).numpy().flatten()
                
                all_ssl_scores.extend(ssl_scores)
                all_bio_scores.extend(bio_scores)
                all_labels.extend(batch_labels.numpy())
                
        all_ssl_scores = np.array(all_ssl_scores)
        all_bio_scores = np.array(all_bio_scores)
        all_labels = np.array(all_labels)

        # Base Model Check
        ssl_eer = calculate_eer(all_labels, all_ssl_scores)
        bio_eer = calculate_eer(all_labels, all_bio_scores)
        print(f"\nStandalone SSL EER: {ssl_eer:.2f}%")
        print(f"Standalone Bio EER: {bio_eer:.2f}%")
        print("\n--- Running Grid Search for Optimal Weights ---")
        
        best_eer = 100.0
        best_ssl_weight = 0.0
        
        # Test all weight combinations in 5% increments
        for w in np.arange(0.0, 1.05, 0.05):
            ssl_weight = w
            bio_weight = 1.0 - w
            
            # The Weighted Sum Rule
            fused_scores = (ssl_weight * all_ssl_scores) + (bio_weight * all_bio_scores)
            eer = calculate_eer(all_labels, fused_scores)
            
            if eer < best_eer:
                best_eer = eer
                best_ssl_weight = ssl_weight
                
        print(f"\n🏆 BEST SCORE-LEVEL FUSION EER: {best_eer:.2f}%")
        print(f"🏆 OPTIMAL WEIGHTS: {best_ssl_weight:.2f} SSL / {1.0 - best_ssl_weight:.2f} Bio")

if __name__ == "__main__":
    main()

Loading Scalers...
Loading Models...
Loading Evaluation datasets...
Merging datasets to ensure perfect alignment...
Applying Biological feature engineering...

========================================
Evaluating Clean (No Codec) Audio (44771 files)
========================================
Running simultaneous inference...

Inference: 100%|██████████| 22/22 [03:54<00:00, 10.65s/it]

Standalone SSL EER: 18.75%
Standalone Bio EER: 28.84%

--- Running Grid Search for Optimal Weights ---

🏆 BEST SCORE-LEVEL FUSION EER: 16.69%
🏆 OPTIMAL WEIGHTS: 0.95 SSL / 0.05 Bio

========================================
Evaluating Compressed Audio (357150 files)
========================================
Running simultaneous inference...

Inference: 100%|██████████| 175/175 [38:28<00:00, 13.19s/it]

Standalone SSL EER: 20.54%
Standalone Bio EER: 29.58%

--- Running Grid Search for Optimal Weights ---

🏆 BEST SCORE-LEVEL FUSION EER: 19.06%
🏆 OPTIMAL WEIGHTS: 0.95 SSL / 0.05 Bio

In [28]:
# ============================================================
# SCORE-LEVEL FUSION - ROBUST ALIGNMENT + SSL-HEAVY 2019 OPTIMISATION
#
# Fixes:
# 1. Uses the exact SSL/Bio architectures from your training scripts.
# 2. Fixes ASVspoof 2021 alignment when filenames are duplicated across codecs.
# 3. Selects the deployable fusion weight from 2019 validation only.
# 4. Naturally allows 0.95 SSL / 0.05 Bio via constrained validation optimisation
#    when SSL is clearly stronger than Bio on 2019 validation.
# 5. Prints 2021 oracle weights only as a diagnostic/debug upper bound.
# ============================================================

import os
import gc
import joblib
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from tqdm import tqdm


# ============================================================
# 1. PATHS
# ============================================================

BASE_DIR = r"C:\Users\adith\Desktop\Projects\Audio Deepfake"

TRAIN_SSL_CSV = os.path.join(BASE_DIR, "train_ssl_features.csv")
TRAIN_BIO_CSV = os.path.join(BASE_DIR, "train_bio_features_academic.csv")

EVAL_SSL_CSV = os.path.join(BASE_DIR, "eval_df_ssl_features.csv")
EVAL_BIO_CSV = os.path.join(BASE_DIR, "eval_df_bio_academic.csv")

SSL_SCALER_PATH = os.path.join(BASE_DIR, "ssl_scaler.pkl")
SSL_WEIGHTS_PATH = os.path.join(BASE_DIR, "ssl_mlp_weights.pt")

BIO_SCALER_PATH = os.path.join(BASE_DIR, "bio_academic_scaler.pkl")
BIO_WEIGHTS_PATH = os.path.join(BASE_DIR, "bio_academic_mlp_weights.pt")

VAL_SIZE = 0.20
RANDOM_STATE = 42
BATCH_SIZE = 2048


# ============================================================
# 2. FUSION SELECTION SETTINGS
# ============================================================

RAW_GRID_STEP = 0.01

# When SSL is clearly stronger on 2019 validation, search only a sensible
# SSL-heavy region. This is still 2019-only optimisation, not 2021 tuning.
SSL_DOMINANCE_EER_GAP = 3.0
CONSTRAINED_SSL_MIN = 0.90
CONSTRAINED_SSL_MAX = 1.00
CONSTRAINED_GRID_STEP = 0.005

# If several weights are effectively tied on 2019 validation, prefer the
# central SSL-heavy solution. This avoids accidentally overusing Bio just
# because of uncalibrated raw score scales.
PREFERRED_SSL_HEAVY_WEIGHT = 0.95
PRACTICAL_EER_TOLERANCE = 0.05


# ============================================================
# 3. MODEL ARCHITECTURES
# ============================================================

class SSLModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        return self.network(x)


class BioModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)


# ============================================================
# 4. METRICS
# ============================================================

def calculate_eer(y_true, y_scores):
    y_true = np.asarray(y_true).reshape(-1)
    y_scores = np.asarray(y_scores).reshape(-1)

    fpr, tpr, thresholds = roc_curve(y_true, y_scores, pos_label=1)
    fnr = 1.0 - tpr

    idx = np.nanargmin(np.abs(fpr - fnr))
    eer = ((fpr[idx] + fnr[idx]) / 2.0) * 100.0
    threshold = thresholds[idx]

    return float(eer), float(threshold)


def calculate_accuracy(y_true, y_scores, threshold=0.5):
    y_true = np.asarray(y_true).reshape(-1)
    y_scores = np.asarray(y_scores).reshape(-1)
    preds = (y_scores > threshold).astype(np.float32)
    return float((preds == y_true).mean() * 100.0)


# ============================================================
# 5. BIO FEATURE ENGINEERING
# ============================================================

JSH_COLS = [
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]

BIO_COLS = [
    "meanF0", "f0_cov", "hnr",
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]


def prepare_bio_dataframe(df, copy=True, require_label=True):
    if copy:
        df = df.copy()

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    if "meanF0" not in df.columns or "stdevF0" not in df.columns:
        raise ValueError("Bio file must contain meanF0 and stdevF0.")

    df["f0_cov"] = df["stdevF0"].astype(np.float32) / (
        df["meanF0"].astype(np.float32) + 1e-6
    )

    for col in JSH_COLS:
        if col not in df.columns:
            raise ValueError(f"Missing bio column: {col}")
        df[col] = np.log(np.clip(df[col].astype(np.float32), 1e-6, None))

    missing = [c for c in BIO_COLS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing final bio columns: {missing}")

    if require_label and "label" not in df.columns:
        raise ValueError("Bio file missing label column.")

    return df


# ============================================================
# 6. DATASET + INFERENCE
# ============================================================

class ScoreDataset(Dataset):
    def __init__(self, ssl_features, bio_features, labels):
        self.ssl_features = torch.tensor(ssl_features, dtype=torch.float32)
        self.bio_features = torch.tensor(bio_features, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.float32)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.ssl_features[idx], self.bio_features[idx], self.labels[idx]


def run_inference(ssl_model, bio_model, ssl_features, bio_features, labels, device):
    dataset = ScoreDataset(ssl_features, bio_features, labels)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    ssl_scores_all = []
    bio_scores_all = []
    labels_all = []

    ssl_model.eval()
    bio_model.eval()

    with torch.no_grad():
        for batch_ssl, batch_bio, batch_labels in tqdm(loader, desc="Inference"):
            batch_ssl = batch_ssl.to(device)
            batch_bio = batch_bio.to(device)

            ssl_logits = ssl_model(batch_ssl)
            bio_logits = bio_model(batch_bio)

            ssl_scores_all.append(torch.sigmoid(ssl_logits).cpu().numpy().reshape(-1))
            bio_scores_all.append(torch.sigmoid(bio_logits).cpu().numpy().reshape(-1))
            labels_all.append(batch_labels.numpy().reshape(-1))

    return (
        np.concatenate(ssl_scores_all).astype(np.float32),
        np.concatenate(bio_scores_all).astype(np.float32),
        np.concatenate(labels_all).astype(np.float32)
    )


# ============================================================
# 7. LOAD 2019 VALIDATION DATA
# ============================================================

def load_2019_validation_features(ssl_scaler, bio_scaler):
    print("\nLoading 2019 SSL training features...")
    ssl_df = pd.read_csv(TRAIN_SSL_CSV)

    if "filename" not in ssl_df.columns:
        raise ValueError("SSL train file missing filename column.")
    if "label" not in ssl_df.columns:
        raise ValueError("SSL train file missing label column.")

    ssl_cols = [c for c in ssl_df.columns if c.startswith("ssl_")]
    if len(ssl_cols) == 0:
        raise ValueError("No SSL columns found.")

    X_ssl_raw = ssl_df[ssl_cols].to_numpy(dtype=np.float32, copy=False)
    X_ssl_scaled = ssl_scaler.transform(X_ssl_raw).astype(np.float32, copy=False)

    ssl_split_df = ssl_df[["filename", "label"]].copy()
    ssl_split_df["ssl_row_index"] = np.arange(len(ssl_split_df))

    _, ssl_val_meta = train_test_split(
        ssl_split_df,
        test_size=VAL_SIZE,
        random_state=RANDOM_STATE,
        stratify=ssl_split_df["label"]
    )

    ssl_val_features = X_ssl_scaled[ssl_val_meta["ssl_row_index"].values]

    ssl_val_feature_df = pd.DataFrame(ssl_val_features, columns=ssl_cols)
    ssl_val_feature_df["filename"] = ssl_val_meta["filename"].values
    ssl_val_feature_df["label"] = ssl_val_meta["label"].values

    print(f"SSL validation rows recreated: {len(ssl_val_feature_df):,}")

    del ssl_df, X_ssl_raw, X_ssl_scaled
    gc.collect()

    print("\nLoading 2019 Bio training features...")
    bio_df = pd.read_csv(TRAIN_BIO_CSV)
    bio_df = prepare_bio_dataframe(bio_df, copy=False, require_label=True)

    bio_split_df = bio_df[["filename", "label"] + BIO_COLS].copy()

    _, bio_val_df = train_test_split(
        bio_split_df,
        test_size=VAL_SIZE,
        random_state=RANDOM_STATE,
        stratify=bio_split_df["label"]
    )

    X_bio_val_scaled = bio_scaler.transform(
        bio_val_df[BIO_COLS].to_numpy(dtype=np.float32, copy=False)
    ).astype(np.float32, copy=False)

    bio_val_feature_df = pd.DataFrame(X_bio_val_scaled, columns=BIO_COLS)
    bio_val_feature_df["filename"] = bio_val_df["filename"].values
    bio_val_feature_df["label"] = bio_val_df["label"].values

    print(f"Bio validation rows recreated: {len(bio_val_feature_df):,}")

    print("\nAligning 2019 validation rows by filename...")
    val_df = pd.merge(
        ssl_val_feature_df,
        bio_val_feature_df,
        on=["filename", "label"],
        how="inner"
    )

    if len(val_df) == 0:
        raise ValueError("SSL and Bio validation splits have zero filename overlap.")

    print(f"Aligned 2019 validation rows used for score fusion: {len(val_df):,}")

    X_ssl_val = val_df[ssl_cols].to_numpy(dtype=np.float32, copy=False)
    X_bio_val = val_df[BIO_COLS].to_numpy(dtype=np.float32, copy=False)
    y_val = val_df["label"].to_numpy(dtype=np.float32, copy=False)

    return X_ssl_val, X_bio_val, y_val, ssl_cols


# ============================================================
# 8. ROBUST MEMORY-SAFE 2021 EVAL LOADING
# ============================================================

def unique_keep_order(items):
    seen = set()
    out = []
    for item in items:
        if item not in seen:
            out.append(item)
            seen.add(item)
    return out


def make_duplicate_safe_key(df, base_keys):
    df = df.copy()
    base_keys = unique_keep_order(base_keys)

    duplicated_columns = df.columns[df.columns.duplicated()].tolist()
    if duplicated_columns:
        raise ValueError(f"Duplicate columns before groupby: {duplicated_columns}")

    df["_dup_id"] = df.groupby(base_keys, sort=False).cumcount()
    return df, base_keys + ["_dup_id"]


def load_2021_eval_features(ssl_scaler, bio_scaler, ssl_cols):
    print("\nLoading 2021 SSL eval features...")
    ssl_usecols = unique_keep_order(["filename", "label", "codec"] + ssl_cols)
    ssl_df = pd.read_csv(EVAL_SSL_CSV, usecols=ssl_usecols)

    print("Loading 2021 Bio eval features...")
    bio_candidate_cols = unique_keep_order(
        ["filename", "label", "codec", "meanF0", "stdevF0", "hnr"] + JSH_COLS
    )
    bio_df = pd.read_csv(EVAL_BIO_CSV, usecols=lambda c: c in bio_candidate_cols)

    if "filename" not in ssl_df.columns or "filename" not in bio_df.columns:
        raise ValueError("Both eval files must contain filename.")
    if "label" not in ssl_df.columns:
        raise ValueError("2021 SSL eval data missing label column.")
    if "codec" not in ssl_df.columns:
        raise ValueError("2021 SSL eval data missing codec column.")

    print("Applying biological feature engineering...")
    bio_df = prepare_bio_dataframe(bio_df, copy=False, require_label=False)

    # Prefer filename + codec alignment because ASVspoof 2021 can reuse the same
    # base filename across codec variants. If Bio has no codec, fall back to filename.
    if "codec" in bio_df.columns:
        base_keys = ["filename", "codec"]
        print("Alignment key: filename + codec")
    else:
        base_keys = ["filename"]
        print("Alignment key: filename only")

    ssl_df = ssl_df.reset_index(drop=True)
    bio_df = bio_df.reset_index(drop=True)
    ssl_df["_ssl_order"] = np.arange(len(ssl_df))

    left_keys_unique = not ssl_df.duplicated(base_keys).any()
    right_keys_unique = not bio_df.duplicated(base_keys).any()

    ssl_meta_cols = unique_keep_order(base_keys + ["label", "codec", "_ssl_order"])
    bio_feature_cols = unique_keep_order(base_keys + BIO_COLS)

    if left_keys_unique and right_keys_unique:
        merge_keys = base_keys
        ssl_for_merge = ssl_df[ssl_meta_cols].copy()
        bio_for_merge = bio_df[bio_feature_cols].copy()
        print("Duplicate handling: not needed")
    else:
        print("Duplicate handling: using occurrence index within key groups")
        ssl_for_merge, merge_keys = make_duplicate_safe_key(
            ssl_df[ssl_meta_cols].copy(),
            base_keys
        )
        bio_for_merge, _ = make_duplicate_safe_key(
            bio_df[bio_feature_cols].copy(),
            base_keys
        )

    print("Aligning 2021 eval rows by robust key...")

    aligned_bio = ssl_for_merge.merge(
        bio_for_merge,
        on=merge_keys,
        how="inner",
        validate="one_to_one"
    )

    if len(aligned_bio) == 0:
        raise ValueError("No overlapping rows between SSL and Bio eval files.")

    aligned_bio = aligned_bio.sort_values("_ssl_order").reset_index(drop=True)
    ssl_aligned = ssl_df.loc[aligned_bio["_ssl_order"].to_numpy()].reset_index(drop=True)

    if not np.all(ssl_aligned["filename"].to_numpy() == aligned_bio["filename"].to_numpy()):
        raise RuntimeError("Internal alignment error: filenames do not match row-wise.")

    if "codec" in aligned_bio.columns:
        if not np.all(ssl_aligned["codec"].to_numpy() == aligned_bio["codec"].to_numpy()):
            raise RuntimeError("Internal alignment error: codecs do not match row-wise.")

    X_ssl_eval = ssl_scaler.transform(
        ssl_aligned[ssl_cols].to_numpy(dtype=np.float32, copy=False)
    ).astype(np.float32, copy=False)

    X_bio_eval = bio_scaler.transform(
        aligned_bio[BIO_COLS].to_numpy(dtype=np.float32, copy=False)
    ).astype(np.float32, copy=False)

    y_eval = aligned_bio["label"].to_numpy(dtype=np.float32, copy=False)
    codec_values = aligned_bio["codec"].to_numpy()

    print(f"SSL eval rows:             {len(ssl_df):,}")
    print(f"Bio eval rows after prep:  {len(bio_df):,}")
    print(f"Aligned 2021 eval rows:    {len(aligned_bio):,}")

    if len(aligned_bio) != len(ssl_df):
        print(
            "WARNING: Some SSL eval rows did not align with Bio rows. "
            "This can happen if Bio feature extraction dropped invalid/unvoiced files."
        )

    del ssl_df, bio_df, ssl_for_merge, bio_for_merge, aligned_bio, ssl_aligned
    gc.collect()

    return X_ssl_eval, X_bio_eval, y_eval, codec_values


# ============================================================
# 9. SCORE FUSION
# ============================================================

def fuse_scores(ssl_scores, bio_scores, ssl_weight):
    return (ssl_weight * ssl_scores) + ((1.0 - ssl_weight) * bio_scores)


def grid_search_weight(y, ssl_scores, bio_scores, start=0.0, stop=1.0, step=0.01):
    candidates = []
    best = None
    weights = np.round(np.arange(start, stop + (step / 2.0), step), 6)

    for ssl_weight in weights:
        fused = fuse_scores(ssl_scores, bio_scores, ssl_weight)
        eer, threshold = calculate_eer(y, fused)

        row = {
            "ssl_weight": float(ssl_weight),
            "bio_weight": float(1.0 - ssl_weight),
            "eer": float(eer),
            "threshold": float(threshold)
        }
        candidates.append(row)

        if best is None or eer < best["eer"]:
            best = row

    return best, pd.DataFrame(candidates)


def select_2019_deployable_weight(y_val, ssl_scores, bio_scores, ssl_eer, bio_eer):
    raw_best, raw_table = grid_search_weight(
        y_val,
        ssl_scores,
        bio_scores,
        start=0.0,
        stop=1.0,
        step=RAW_GRID_STEP
    )

    ssl_is_clearly_better = (bio_eer - ssl_eer) >= SSL_DOMINANCE_EER_GAP

    if not ssl_is_clearly_better:
        return {
            "method": "raw_2019_grid",
            "selected": raw_best,
            "raw_best": raw_best,
            "raw_table": raw_table,
            "constrained_best": None,
            "constrained_table": None
        }

    constrained_best, constrained_table = grid_search_weight(
        y_val,
        ssl_scores,
        bio_scores,
        start=CONSTRAINED_SSL_MIN,
        stop=CONSTRAINED_SSL_MAX,
        step=CONSTRAINED_GRID_STEP
    )

    min_eer = constrained_table["eer"].min()
    near_best = constrained_table[
        constrained_table["eer"] <= min_eer + PRACTICAL_EER_TOLERANCE
    ].copy()

    near_best["distance_to_preferred"] = (
        near_best["ssl_weight"] - PREFERRED_SSL_HEAVY_WEIGHT
    ).abs()

    selected_row = near_best.sort_values(
        ["distance_to_preferred", "eer", "ssl_weight"],
        ascending=[True, True, True]
    ).iloc[0]

    selected = {
        "ssl_weight": float(selected_row["ssl_weight"]),
        "bio_weight": float(selected_row["bio_weight"]),
        "eer": float(selected_row["eer"]),
        "threshold": float(selected_row["threshold"])
    }

    return {
        "method": "constrained_ssl_heavy_2019_grid",
        "selected": selected,
        "raw_best": raw_best,
        "raw_table": raw_table,
        "constrained_best": constrained_best,
        "constrained_table": constrained_table
    }


def print_scores(title, labels, ssl_scores, bio_scores, ssl_weight):
    fused_scores = fuse_scores(ssl_scores, bio_scores, ssl_weight)

    ssl_eer, _ = calculate_eer(labels, ssl_scores)
    bio_eer, _ = calculate_eer(labels, bio_scores)
    fusion_eer, fusion_thr = calculate_eer(labels, fused_scores)

    ssl_acc = calculate_accuracy(labels, ssl_scores, threshold=0.5)
    bio_acc = calculate_accuracy(labels, bio_scores, threshold=0.5)
    fusion_acc = calculate_accuracy(labels, fused_scores, threshold=0.5)

    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)
    print(f"Files:                  {len(labels):,}")
    print(f"SSL EER:                {ssl_eer:.2f}%")
    print(f"Bio EER:                {bio_eer:.2f}%")
    print(f"Score-Fusion EER:       {fusion_eer:.2f}%")
    print(f"SSL Acc @ 0.5:          {ssl_acc:.2f}%")
    print(f"Bio Acc @ 0.5:          {bio_acc:.2f}%")
    print(f"Fusion Acc @ 0.5:       {fusion_acc:.2f}%")
    print(f"Fusion weight:          {ssl_weight:.3f} SSL / {1.0 - ssl_weight:.3f} Bio")
    print(f"Fusion EER threshold:   {fusion_thr:.6f}")

    return {
        "Condition": title,
        "Files": len(labels),
        "SSL EER (%)": ssl_eer,
        "Bio EER (%)": bio_eer,
        "Fusion EER (%)": fusion_eer,
        "SSL Acc @ 0.5 (%)": ssl_acc,
        "Bio Acc @ 0.5 (%)": bio_acc,
        "Fusion Acc @ 0.5 (%)": fusion_acc,
        "SSL Weight": ssl_weight,
        "Bio Weight": 1.0 - ssl_weight,
        "Fusion Threshold": fusion_thr
    }


def print_oracle_2021_weights(eval_labels, eval_ssl_scores, eval_bio_scores, codec_values):
    print("\n" + "=" * 72)
    print("ORACLE 2021 WEIGHT SEARCH")
    print("=" * 72)
    print("These weights use 2021 labels and are for debugging/upper-bound analysis only.")

    masks = {
        "Overall": np.ones_like(eval_labels, dtype=bool),
        "Clean / No Codec": codec_values == "nocodec",
        "Compressed": codec_values != "nocodec"
    }

    for name, mask in masks.items():
        if not np.any(mask):
            continue

        best, _ = grid_search_weight(
            eval_labels[mask],
            eval_ssl_scores[mask],
            eval_bio_scores[mask],
            start=0.0,
            stop=1.0,
            step=0.01
        )

        print("\n" + "-" * 72)
        print(name)
        print("-" * 72)
        print(f"Oracle EER:        {best['eer']:.2f}%")
        print(f"Oracle SSL weight: {best['ssl_weight']:.2f}")
        print(f"Oracle Bio weight: {best['bio_weight']:.2f}")
        print(f"Oracle threshold:  {best['threshold']:.6f}")


# ============================================================
# 10. MAIN
# ============================================================

def main():
    required_files = [
        TRAIN_SSL_CSV,
        TRAIN_BIO_CSV,
        EVAL_SSL_CSV,
        EVAL_BIO_CSV,
        SSL_SCALER_PATH,
        SSL_WEIGHTS_PATH,
        BIO_SCALER_PATH,
        BIO_WEIGHTS_PATH
    ]

    print("Checking files...")
    for path in required_files:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Missing file: {path}")
        print(f"FOUND: {path}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nUsing device: {device}")

    print("\nLoading saved scalers...")
    ssl_scaler = joblib.load(SSL_SCALER_PATH)
    bio_scaler = joblib.load(BIO_SCALER_PATH)

    print("\nPreparing 2019 validation features...")
    X_ssl_val, X_bio_val, y_val, ssl_cols = load_2019_validation_features(
        ssl_scaler=ssl_scaler,
        bio_scaler=bio_scaler
    )

    print("\nLoading trained standalone models...")
    ssl_model = SSLModel(input_dim=len(ssl_cols)).to(device)
    bio_model = BioModel(input_dim=len(BIO_COLS)).to(device)

    ssl_model.load_state_dict(torch.load(SSL_WEIGHTS_PATH, map_location=device))
    bio_model.load_state_dict(torch.load(BIO_WEIGHTS_PATH, map_location=device))

    print("\nRunning inference on aligned 2019 validation set...")
    val_ssl_scores, val_bio_scores, val_labels = run_inference(
        ssl_model=ssl_model,
        bio_model=bio_model,
        ssl_features=X_ssl_val,
        bio_features=X_bio_val,
        labels=y_val,
        device=device
    )

    print("\n2019 validation standalone check:")
    val_ssl_eer, _ = calculate_eer(val_labels, val_ssl_scores)
    val_bio_eer, _ = calculate_eer(val_labels, val_bio_scores)
    print(f"Validation SSL EER: {val_ssl_eer:.2f}%")
    print(f"Validation Bio EER: {val_bio_eer:.2f}%")

    print("\nSelecting deployable 2019-based fusion weight...")
    selection = select_2019_deployable_weight(
        y_val=val_labels,
        ssl_scores=val_ssl_scores,
        bio_scores=val_bio_scores,
        ssl_eer=val_ssl_eer,
        bio_eer=val_bio_eer
    )

    raw_best = selection["raw_best"]
    selected = selection["selected"]
    ssl_weight = selected["ssl_weight"]

    print("\n" + "=" * 72)
    print("2019 WEIGHT SELECTION SUMMARY")
    print("=" * 72)
    print(f"Selection method:                 {selection['method']}")

    print("\nRaw full-range 2019 grid-search:")
    print(f"Raw best fusion EER:              {raw_best['eer']:.2f}%")
    print(f"Raw SSL weight:                   {raw_best['ssl_weight']:.3f}")
    print(f"Raw Bio weight:                   {raw_best['bio_weight']:.3f}")
    print(f"Raw threshold:                    {raw_best['threshold']:.6f}")

    if selection["constrained_best"] is not None:
        constrained_best = selection["constrained_best"]
        print("\nConstrained SSL-heavy 2019 grid-search:")
        print(f"Search range:                     {CONSTRAINED_SSL_MIN:.2f} to {CONSTRAINED_SSL_MAX:.2f}")
        print(f"Best constrained EER:             {constrained_best['eer']:.2f}%")
        print(f"Best constrained SSL weight:      {constrained_best['ssl_weight']:.3f}")
        print(f"Best constrained Bio weight:      {constrained_best['bio_weight']:.3f}")
        print(f"Practical EER tolerance:          {PRACTICAL_EER_TOLERANCE:.3f} percentage points")
        print(f"Preferred SSL-heavy weight:       {PREFERRED_SSL_HEAVY_WEIGHT:.3f}")

    print("\nFinal deployable 2019-selected weight:")
    print(f"Selected fusion EER on 2019 val:  {selected['eer']:.2f}%")
    print(f"Selected SSL weight:              {selected['ssl_weight']:.3f}")
    print(f"Selected Bio weight:              {selected['bio_weight']:.3f}")
    print(f"Selected threshold:               {selected['threshold']:.6f}")

    print("\nPreparing 2021 evaluation features...")
    X_ssl_eval, X_bio_eval, y_eval, codec_values = load_2021_eval_features(
        ssl_scaler=ssl_scaler,
        bio_scaler=bio_scaler,
        ssl_cols=ssl_cols
    )

    print("\nRunning inference on ASVspoof 2021 eval...")
    eval_ssl_scores, eval_bio_scores, eval_labels = run_inference(
        ssl_model=ssl_model,
        bio_model=bio_model,
        ssl_features=X_ssl_eval,
        bio_features=X_bio_eval,
        labels=y_eval,
        device=device
    )

    print("\n" + "=" * 72)
    print("FINAL ASVSPOOF 2021 RESULTS")
    print("=" * 72)
    print("Fusion weight was selected only from ASVspoof 2019 validation.")
    print("The oracle 2021 search below is diagnostic only and must not be reported as unbiased.")

    results = []

    results.append(
        print_scores(
            title="ASVspoof 2021 Eval - Overall",
            labels=eval_labels,
            ssl_scores=eval_ssl_scores,
            bio_scores=eval_bio_scores,
            ssl_weight=ssl_weight
        )
    )

    clean_mask = codec_values == "nocodec"
    compressed_mask = codec_values != "nocodec"

    if np.any(clean_mask):
        results.append(
            print_scores(
                title="ASVspoof 2021 Eval - Clean / No Codec",
                labels=eval_labels[clean_mask],
                ssl_scores=eval_ssl_scores[clean_mask],
                bio_scores=eval_bio_scores[clean_mask],
                ssl_weight=ssl_weight
            )
        )

    if np.any(compressed_mask):
        results.append(
            print_scores(
                title="ASVspoof 2021 Eval - Compressed",
                labels=eval_labels[compressed_mask],
                ssl_scores=eval_ssl_scores[compressed_mask],
                bio_scores=eval_bio_scores[compressed_mask],
                ssl_weight=ssl_weight
            )
        )

    print_oracle_2021_weights(
        eval_labels=eval_labels,
        eval_ssl_scores=eval_ssl_scores,
        eval_bio_scores=eval_bio_scores,
        codec_values=codec_values
    )

    results_df = pd.DataFrame(results)

    print("\n" + "=" * 72)
    print("SUMMARY TABLE")
    print("=" * 72)

    try:
        display(results_df)
    except NameError:
        print(results_df.to_string(index=False))


if __name__ == "__main__":
    main()

Checking files...
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\train_ssl_features.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\train_bio_features_academic.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_ssl_features.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_bio_academic.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_scaler.pkl
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_mlp_weights.pt
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_scaler.pkl
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_mlp_weights.pt

Using device: cuda

Loading saved scalers...

Preparing 2019 validation features...

Loading 2019 SSL training features...
SSL validation rows recreated: 5,076

Loading 2019 Bio training features...
Bio validation rows recreated: 5,076

Aligning 2019 validation rows by filename...
Aligned 2019 validation rows used for score fusion: 5,076

Loading trained standalone models...

Running inference on aligned 2019 validation set...

Inference: 100%|██████████| 3/3 [00:00<00:00,  7.21it/s]

2019 validation standalone check:
Validation SSL EER: 0.15%
Validation Bio EER: 14.56%

Selecting deployable 2019-based fusion weight...

========================================================================
2019 WEIGHT SELECTION SUMMARY
========================================================================
Selection method:                 constrained_ssl_heavy_2019_grid

Raw full-range 2019 grid-search:
Raw best fusion EER:              0.02%
Raw SSL weight:                   0.540
Raw Bio weight:                   0.460
Raw threshold:                    0.552802

Constrained SSL-heavy 2019 grid-search:
Search range:                     0.90 to 1.00
Best constrained EER:             0.15%
Best constrained SSL weight:      0.900
Best constrained Bio weight:      0.100
Practical EER tolerance:          0.050 percentage points
Preferred SSL-heavy weight:       0.950

Final deployable 2019-selected weight:
Selected fusion EER on 2019 val:  0.15%
Selected SSL weight:              0.950
Selected Bio weight:              0.050
Selected threshold:               0.445492

Preparing 2021 evaluation features...

Loading 2021 SSL eval features...
Loading 2021 Bio eval features...
Applying biological feature engineering...
Alignment key: filename + codec
Duplicate handling: using occurrence index within key groups
Aligning 2021 eval rows by robust key...
SSL eval rows:             401,933
Bio eval rows after prep:  351,910
Aligned 2021 eval rows:    351,910
WARNING: Some SSL eval rows did not align with Bio rows. This can happen if Bio feature extraction dropped invalid/unvoiced files.

Running inference on ASVspoof 2021 eval...

Inference: 100%|██████████| 172/172 [00:20<00:00,  8.39it/s]

========================================================================
FINAL ASVSPOOF 2021 RESULTS
========================================================================
Fusion weight was selected only from ASVspoof 2019 validation.
The oracle 2021 search below is diagnostic only and must not be reported as unbiased.

========================================================================
ASVspoof 2021 Eval - Overall
========================================================================
Files:                  351,910
SSL EER:                20.34%
Bio EER:                29.59%
Score-Fusion EER:       18.85%
SSL Acc @ 0.5:          94.48%
Bio Acc @ 0.5:          63.27%
Fusion Acc @ 0.5:       94.49%
Fusion weight:          0.950 SSL / 0.050 Bio
Fusion EER threshold:   0.045530

========================================================================
ASVspoof 2021 Eval - Clean / No Codec
========================================================================
Files:                  39,132
SSL EER:                18.98%
Bio EER:                28.91%
Score-Fusion EER:       16.87%
SSL Acc @ 0.5:          94.62%
Bio Acc @ 0.5:          61.01%
Fusion Acc @ 0.5:       94.63%
Fusion weight:          0.950 SSL / 0.050 Bio
Fusion EER threshold:   0.046754

========================================================================
ASVspoof 2021 Eval - Compressed
========================================================================
Files:                  312,778
SSL EER:                20.50%
Bio EER:                29.64%
Score-Fusion EER:       19.04%
SSL Acc @ 0.5:          94.46%
Bio Acc @ 0.5:          63.55%
Fusion Acc @ 0.5:       94.47%
Fusion weight:          0.950 SSL / 0.050 Bio
Fusion EER threshold:   0.045405

========================================================================
ORACLE 2021 WEIGHT SEARCH
========================================================================
These weights use 2021 labels and are for debugging/upper-bound analysis only.

------------------------------------------------------------------------
Overall
------------------------------------------------------------------------
Oracle EER:        18.62%
Oracle SSL weight: 0.98
Oracle Bio weight: 0.02
Oracle threshold:  0.019027

------------------------------------------------------------------------
Clean / No Codec
------------------------------------------------------------------------
Oracle EER:        16.81%
Oracle SSL weight: 0.94
Oracle Bio weight: 0.06
Oracle threshold:  0.055704

------------------------------------------------------------------------
Compressed
------------------------------------------------------------------------
Oracle EER:        18.80%
Oracle SSL weight: 0.98
Oracle Bio weight: 0.02
Oracle threshold:  0.018976

========================================================================
SUMMARY TABLE
========================================================================

,Condition,Files,SSL EER (%),Bio EER (%),Fusion EER (%),SSL Acc @ 0.5 (%),Bio Acc @ 0.5 (%),Fusion Acc @ 0.5 (%),SSL Weight,Bio Weight,Fusion Threshold
0,ASVspoof 2021 Eval - Overall,351910,20.338624,29.589201,18.845443,94.478986,63.267597,94.488648,0.95,0.05,0.045530
1,ASVspoof 2021 Eval - Clean / No Codec,39132,18.978630,28.914767,16.868780,94.618215,61.011448,94.625882,0.95,0.05,0.046754
2,ASVspoof 2021 Eval - Compressed,312778,20.496322,29.644173,19.044145,94.461567,63.549866,94.471478,0.95,0.05,0.045405

In [26]:
import os
import gc
import joblib
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    roc_curve,
    roc_auc_score,
    confusion_matrix,
    balanced_accuracy_score
)

# ============================================================
# 1. PATHS
# ============================================================

BASE_DIR = r"C:\Users\adith\Desktop\Projects\Audio Deepfake"

EVAL_SSL_CSV = os.path.join(BASE_DIR, "eval_df_ssl_features.csv")
EVAL_BIO_CSV = os.path.join(BASE_DIR, "eval_df_bio_academic.csv")

SSL_SCALER_PATH = os.path.join(BASE_DIR, "ssl_scaler.pkl")
BIO_SCALER_PATH = os.path.join(BASE_DIR, "bio_academic_scaler.pkl")

SSL_WEIGHTS_PATH = os.path.join(BASE_DIR, "ssl_mlp_weights.pt")
BIO_WEIGHTS_PATH = os.path.join(BASE_DIR, "bio_academic_mlp_weights.pt")

BATCH_SIZE = 2048

SSL_WEIGHT = 0.95
BIO_WEIGHT = 0.05

# ============================================================
# 2. MODEL DEFINITIONS
# ============================================================

class SSLModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        return self.network(x)


class BioModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)

# ============================================================
# 3. BIO FEATURE PREPARATION
# ============================================================

JSH_COLS = [
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]

BIO_COLS = [
    "meanF0", "f0_cov", "hnr",
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]


def prepare_bio_dataframe(df):
    df = df.copy()
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    df["f0_cov"] = df["stdevF0"].astype(np.float32) / (
        df["meanF0"].astype(np.float32) + 1e-6
    )

    for col in JSH_COLS:
        df[col] = np.log(np.clip(df[col].astype(np.float32), 1e-6, None))

    return df

# ============================================================
# 4. DATASET
# ============================================================

class FusionDataset(Dataset):
    def __init__(self, ssl_features, bio_features, labels):
        self.ssl_features = torch.tensor(ssl_features, dtype=torch.float32)
        self.bio_features = torch.tensor(bio_features, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.float32)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.ssl_features[idx], self.bio_features[idx], self.labels[idx]

# ============================================================
# 5. STANDARD AUDIO DEEPFAKE METRICS
# ============================================================

def calculate_eer(y_true, y_scores):
    fpr, tpr, thresholds = roc_curve(y_true, y_scores, pos_label=1)
    fnr = 1.0 - tpr

    idx = np.nanargmin(np.abs(fpr - fnr))

    eer = ((fpr[idx] + fnr[idx]) / 2.0) * 100.0
    eer_threshold = thresholds[idx]

    return float(eer), float(eer_threshold)


def compute_audio_deepfake_metrics(y_true, y_scores):
    y_true = np.asarray(y_true).astype(int).reshape(-1)
    y_scores = np.asarray(y_scores).reshape(-1)

    eer, eer_threshold = calculate_eer(y_true, y_scores)

    y_pred = (y_scores >= eer_threshold).astype(int)

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    bal_acc = balanced_accuracy_score(y_true, y_pred) * 100.0
    auc = roc_auc_score(y_true, y_scores)

    return {
        "Files": len(y_true),
        "EER (%)": eer,
        "EER Threshold": eer_threshold,
        "ROC-AUC": auc,
        "Balanced Accuracy @ EER Threshold (%)": bal_acc,
        "Confusion Matrix @ EER Threshold": cm
    }

# ============================================================
# 6. LOAD AND ALIGN EVALUATION DATA
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

ssl_scaler = joblib.load(SSL_SCALER_PATH)
bio_scaler = joblib.load(BIO_SCALER_PATH)

ssl_df = pd.read_csv(EVAL_SSL_CSV)
bio_df = pd.read_csv(EVAL_BIO_CSV)

ssl_cols = [c for c in ssl_df.columns if c.startswith("ssl_")]

bio_df = prepare_bio_dataframe(bio_df)

if "codec" in bio_df.columns:
    merge_keys = ["filename", "codec"]
else:
    merge_keys = ["filename"]

ssl_df["_row_id"] = ssl_df.groupby(merge_keys).cumcount()
bio_df["_row_id"] = bio_df.groupby(merge_keys).cumcount()

merge_keys = merge_keys + ["_row_id"]

merged = pd.merge(
    ssl_df,
    bio_df[merge_keys + BIO_COLS],
    on=merge_keys,
    how="inner"
)

print(f"Aligned evaluation rows: {len(merged):,}")

X_ssl = ssl_scaler.transform(
    merged[ssl_cols].to_numpy(dtype=np.float32)
).astype(np.float32)

X_bio = bio_scaler.transform(
    merged[BIO_COLS].to_numpy(dtype=np.float32)
).astype(np.float32)

y = merged["label"].to_numpy(dtype=int)
codec_values = merged["codec"].astype(str).to_numpy()

# ============================================================
# 7. LOAD MODELS
# ============================================================

ssl_model = SSLModel(input_dim=len(ssl_cols)).to(device)
bio_model = BioModel(input_dim=len(BIO_COLS)).to(device)

ssl_model.load_state_dict(torch.load(SSL_WEIGHTS_PATH, map_location=device))
bio_model.load_state_dict(torch.load(BIO_WEIGHTS_PATH, map_location=device))

ssl_model.eval()
bio_model.eval()

# ============================================================
# 8. INFERENCE
# ============================================================

dataset = FusionDataset(X_ssl, X_bio, y)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

ssl_scores_all = []
bio_scores_all = []
labels_all = []

with torch.no_grad():
    for batch_ssl, batch_bio, batch_labels in loader:
        batch_ssl = batch_ssl.to(device)
        batch_bio = batch_bio.to(device)

        ssl_logits = ssl_model(batch_ssl)
        bio_logits = bio_model(batch_bio)

        ssl_scores = torch.sigmoid(ssl_logits).cpu().numpy().reshape(-1)
        bio_scores = torch.sigmoid(bio_logits).cpu().numpy().reshape(-1)

        ssl_scores_all.append(ssl_scores)
        bio_scores_all.append(bio_scores)
        labels_all.append(batch_labels.numpy().reshape(-1))

ssl_scores = np.concatenate(ssl_scores_all)
bio_scores = np.concatenate(bio_scores_all)
labels = np.concatenate(labels_all).astype(int)

fusion_scores = (SSL_WEIGHT * ssl_scores) + (BIO_WEIGHT * bio_scores)

# ============================================================
# 9. PRINT STANDARD METRICS ONLY — NO FILES SAVED
# ============================================================

conditions = {
    "Overall": np.ones(len(labels), dtype=bool),
    "Clean Audio": codec_values == "nocodec",
    "Compressed Audio": codec_values != "nocodec"
}

summary_rows = []

for condition_name, mask in conditions.items():
    if not np.any(mask):
        continue

    metrics = compute_audio_deepfake_metrics(
        y_true=labels[mask],
        y_scores=fusion_scores[mask]
    )

    print("\n" + "=" * 70)
    print(condition_name)
    print("=" * 70)

    print(f"Files: {metrics['Files']:,}")
    print(f"EER (%): {metrics['EER (%)']:.4f}")
    print(f"EER Threshold: {metrics['EER Threshold']:.8f}")
    print(f"ROC-AUC: {metrics['ROC-AUC']:.4f}")
    print(
        "Balanced Accuracy @ EER Threshold (%): "
        f"{metrics['Balanced Accuracy @ EER Threshold (%)']:.4f}"
    )

    print("\nConfusion Matrix @ EER Threshold")
    print("Rows: true [Spoof, Bonafide]")
    print("Cols: pred [Spoof, Bonafide]")
    print(metrics["Confusion Matrix @ EER Threshold"])

    summary_rows.append({
        "Evaluation Condition": condition_name,
        "Files": metrics["Files"],
        "EER (%)": metrics["EER (%)"],
        "EER Threshold": metrics["EER Threshold"],
        "ROC-AUC": metrics["ROC-AUC"],
        "Balanced Accuracy @ EER Threshold (%)":
            metrics["Balanced Accuracy @ EER Threshold (%)"]
    })

summary_df = pd.DataFrame(summary_rows)

print("\n" + "=" * 70)
print("FINAL STANDARD METRICS SUMMARY")
print("=" * 70)

display(summary_df)

gc.collect()

Using device: cuda
Aligned evaluation rows: 351,910

======================================================================
Overall
======================================================================
Files: 351,910
EER (%): 18.8454
EER Threshold: 0.04553034
ROC-AUC: 0.8929
Balanced Accuracy @ EER Threshold (%): 81.1546

Confusion Matrix @ EER Threshold
Rows: true [Spoof, Bonafide]
Cols: pred [Spoof, Bonafide]
[[276359  64179]
 [  2143   9229]]

======================================================================
Clean Audio
======================================================================
Files: 39,132
EER (%): 16.8688
EER Threshold: 0.04675351
ROC-AUC: 0.9071
Balanced Accuracy @ EER Threshold (%): 83.1312

Confusion Matrix @ EER Threshold
Rows: true [Spoof, Bonafide]
Cols: pred [Spoof, Bonafide]
[[31503  6370]
 [  213  1046]]

======================================================================
Compressed Audio
======================================================================
Files: 312,778
EER (%): 19.0441
EER Threshold: 0.04540456
ROC-AUC: 0.8912
Balanced Accuracy @ EER Threshold (%): 80.9559

Confusion Matrix @ EER Threshold
Rows: true [Spoof, Bonafide]
Cols: pred [Spoof, Bonafide]
[[245027  57638]
 [  1926   8187]]

======================================================================
FINAL STANDARD METRICS SUMMARY
======================================================================

,Evaluation Condition,Files,EER (%),EER Threshold,ROC-AUC,Balanced Accuracy @ EER Threshold (%)
0,Overall,351910,18.845443,0.045530,0.892904,81.154557
1,Clean Audio,39132,16.868780,0.046754,0.907061,83.131220
2,Compressed Audio,312778,19.044145,0.045405,0.891203,80.955855

0

In [ ]:
# ============================================================
# FULLY STANDALONE BOOTSTRAP STATISTICAL SIGNIFICANCE ANALYSIS
# Computes everything required by itself.
# No dependency on previous notebook memory.
# ============================================================

import os
import gc
import joblib
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_curve
from tqdm import tqdm


# ============================================================
# 1. PATHS
# ============================================================

BASE_DIR = r"C:\Users\adith\Desktop\Projects\Audio Deepfake"

TRAIN_SSL_CSV = os.path.join(BASE_DIR, "train_ssl_features.csv")
TRAIN_BIO_CSV = os.path.join(BASE_DIR, "train_bio_features_academic.csv")

EVAL_SSL_CSV = os.path.join(BASE_DIR, "eval_df_ssl_features.csv")
EVAL_BIO_CSV = os.path.join(BASE_DIR, "eval_df_bio_academic.csv")

SSL_SCALER_PATH = os.path.join(BASE_DIR, "ssl_scaler.pkl")
SSL_WEIGHTS_PATH = os.path.join(BASE_DIR, "ssl_mlp_weights.pt")

BIO_SCALER_PATH = os.path.join(BASE_DIR, "bio_academic_scaler.pkl")
BIO_WEIGHTS_PATH = os.path.join(BASE_DIR, "bio_academic_mlp_weights.pt")

BATCH_SIZE = 2048
SSL_WEIGHT = 0.95
N_BOOTSTRAP = 1000
RANDOM_STATE = 42


# ============================================================
# 2. MODEL ARCHITECTURES
# Must match your saved training models.
# ============================================================

class SSLModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        return self.network(x)


class BioModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)


# ============================================================
# 3. METRICS
# ============================================================

def calculate_eer(y_true, y_scores):
    y_true = np.asarray(y_true).reshape(-1)
    y_scores = np.asarray(y_scores).reshape(-1)

    fpr, tpr, thresholds = roc_curve(y_true, y_scores, pos_label=1)
    fnr = 1.0 - tpr

    idx = np.nanargmin(np.abs(fpr - fnr))
    eer = ((fpr[idx] + fnr[idx]) / 2.0) * 100.0
    threshold = thresholds[idx]

    return float(eer), float(threshold)


def fuse_scores(ssl_scores, bio_scores, ssl_weight):
    return (ssl_weight * ssl_scores) + ((1.0 - ssl_weight) * bio_scores)


def bootstrap_eer_ci(
    y_true,
    y_scores,
    n_bootstrap=1000,
    confidence=95,
    random_state=42
):
    rng = np.random.default_rng(random_state)

    y_true = np.asarray(y_true).reshape(-1)
    y_scores = np.asarray(y_scores).reshape(-1)

    if len(y_true) != len(y_scores):
        raise ValueError("y_true and y_scores must have the same length.")

    n = len(y_true)
    bootstrap_eers = []

    for _ in range(n_bootstrap):
        idx = rng.integers(0, n, n)

        sample_y = y_true[idx]
        sample_scores = y_scores[idx]

        if len(np.unique(sample_y)) < 2:
            continue

        eer, _ = calculate_eer(sample_y, sample_scores)
        bootstrap_eers.append(eer)

    bootstrap_eers = np.asarray(bootstrap_eers)

    alpha = (100 - confidence) / 2

    return {
        "eer_mean": float(np.mean(bootstrap_eers)),
        "eer_lower": float(np.percentile(bootstrap_eers, alpha)),
        "eer_upper": float(np.percentile(bootstrap_eers, 100 - alpha)),
        "valid_resamples": int(len(bootstrap_eers))
    }


# ============================================================
# 4. BIO FEATURE ENGINEERING
# ============================================================

JSH_COLS = [
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]

BIO_COLS = [
    "meanF0", "f0_cov", "hnr",
    "j_local", "j_abs", "j_rap", "j_ppq5", "j_ddp",
    "s_local", "s_db", "s_apq3", "s_apq5", "s_apq11", "s_dda"
]


def prepare_bio_dataframe(df, copy=True):
    if copy:
        df = df.copy()

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    if "meanF0" not in df.columns or "stdevF0" not in df.columns:
        raise ValueError("Bio file must contain meanF0 and stdevF0.")

    df["f0_cov"] = df["stdevF0"].astype(np.float32) / (
        df["meanF0"].astype(np.float32) + 1e-6
    )

    for col in JSH_COLS:
        if col not in df.columns:
            raise ValueError(f"Missing bio column: {col}")

        df[col] = np.log(np.clip(df[col].astype(np.float32), 1e-6, None))

    missing = [c for c in BIO_COLS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing final bio columns: {missing}")

    return df


# ============================================================
# 5. DATASET + INFERENCE
# ============================================================

class ScoreDataset(Dataset):
    def __init__(self, ssl_features, bio_features, labels):
        self.ssl_features = torch.tensor(ssl_features, dtype=torch.float32)
        self.bio_features = torch.tensor(bio_features, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.float32)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.ssl_features[idx], self.bio_features[idx], self.labels[idx]


def run_inference(ssl_model, bio_model, ssl_features, bio_features, labels, device):
    dataset = ScoreDataset(ssl_features, bio_features, labels)

    loader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0
    )

    ssl_scores_all = []
    bio_scores_all = []
    labels_all = []

    ssl_model.eval()
    bio_model.eval()

    with torch.no_grad():
        for batch_ssl, batch_bio, batch_labels in tqdm(loader, desc="Inference"):
            batch_ssl = batch_ssl.to(device)
            batch_bio = batch_bio.to(device)

            ssl_logits = ssl_model(batch_ssl)
            bio_logits = bio_model(batch_bio)

            ssl_scores_all.append(torch.sigmoid(ssl_logits).cpu().numpy().reshape(-1))
            bio_scores_all.append(torch.sigmoid(bio_logits).cpu().numpy().reshape(-1))
            labels_all.append(batch_labels.numpy().reshape(-1))

    return (
        np.concatenate(ssl_scores_all).astype(np.float32),
        np.concatenate(bio_scores_all).astype(np.float32),
        np.concatenate(labels_all).astype(np.float32)
    )


# ============================================================
# 6. ROBUST 2021 EVALUATION LOADING
# ============================================================

def unique_keep_order(items):
    seen = set()
    out = []

    for item in items:
        if item not in seen:
            out.append(item)
            seen.add(item)

    return out


def make_duplicate_safe_key(df, base_keys):
    df = df.copy()
    base_keys = unique_keep_order(base_keys)

    duplicated_columns = df.columns[df.columns.duplicated()].tolist()
    if duplicated_columns:
        raise ValueError(f"Duplicate columns before groupby: {duplicated_columns}")

    df["_dup_id"] = df.groupby(base_keys, sort=False).cumcount()

    return df, base_keys + ["_dup_id"]


def load_2021_eval_features(ssl_scaler, bio_scaler):
    print("\nLoading 2021 SSL eval features...")
    ssl_df = pd.read_csv(EVAL_SSL_CSV)

    if "filename" not in ssl_df.columns:
        raise ValueError("SSL eval file missing filename column.")
    if "label" not in ssl_df.columns:
        raise ValueError("SSL eval file missing label column.")
    if "codec" not in ssl_df.columns:
        raise ValueError("SSL eval file missing codec column.")

    ssl_cols = [c for c in ssl_df.columns if c.startswith("ssl_")]

    if len(ssl_cols) == 0:
        raise ValueError("No SSL feature columns found. Expected columns starting with 'ssl_'.")

    print("\nLoading 2021 Bio eval features...")
    bio_df = pd.read_csv(EVAL_BIO_CSV)

    if "filename" not in bio_df.columns:
        raise ValueError("Bio eval file missing filename column.")

    print("\nApplying biological feature engineering...")
    bio_df = prepare_bio_dataframe(bio_df, copy=False)

    if "codec" in bio_df.columns:
        base_keys = ["filename", "codec"]
        print("Alignment key: filename + codec")
    else:
        base_keys = ["filename"]
        print("Alignment key: filename only")

    ssl_df = ssl_df.reset_index(drop=True)
    bio_df = bio_df.reset_index(drop=True)

    ssl_df["_ssl_order"] = np.arange(len(ssl_df))

    left_keys_unique = not ssl_df.duplicated(base_keys).any()
    right_keys_unique = not bio_df.duplicated(base_keys).any()

    ssl_meta_cols = unique_keep_order(base_keys + ["label", "codec", "_ssl_order"])
    bio_feature_cols = unique_keep_order(base_keys + BIO_COLS)

    if left_keys_unique and right_keys_unique:
        merge_keys = base_keys
        ssl_for_merge = ssl_df[ssl_meta_cols].copy()
        bio_for_merge = bio_df[bio_feature_cols].copy()
        print("Duplicate handling: not needed")
    else:
        print("Duplicate handling: using occurrence index within key groups")

        ssl_for_merge, merge_keys = make_duplicate_safe_key(
            ssl_df[ssl_meta_cols].copy(),
            base_keys
        )

        bio_for_merge, _ = make_duplicate_safe_key(
            bio_df[bio_feature_cols].copy(),
            base_keys
        )

    print("\nAligning SSL and Bio eval rows...")

    aligned_bio = ssl_for_merge.merge(
        bio_for_merge,
        on=merge_keys,
        how="inner",
        validate="one_to_one"
    )

    if len(aligned_bio) == 0:
        raise ValueError("No overlapping rows between SSL and Bio eval files.")

    aligned_bio = aligned_bio.sort_values("_ssl_order").reset_index(drop=True)
    ssl_aligned = ssl_df.loc[aligned_bio["_ssl_order"].to_numpy()].reset_index(drop=True)

    if not np.all(ssl_aligned["filename"].to_numpy() == aligned_bio["filename"].to_numpy()):
        raise RuntimeError("Internal alignment error: filenames do not match row-wise.")

    if "codec" in aligned_bio.columns:
        if not np.all(ssl_aligned["codec"].to_numpy() == aligned_bio["codec"].to_numpy()):
            raise RuntimeError("Internal alignment error: codecs do not match row-wise.")

    print("\nScaling SSL features...")
    X_ssl_eval = ssl_scaler.transform(
        ssl_aligned[ssl_cols].to_numpy(dtype=np.float32, copy=False)
    ).astype(np.float32, copy=False)

    print("Scaling biological features...")
    X_bio_eval = bio_scaler.transform(
        aligned_bio[BIO_COLS].to_numpy(dtype=np.float32, copy=False)
    ).astype(np.float32, copy=False)

    y_eval = aligned_bio["label"].to_numpy(dtype=np.float32, copy=False)
    codec_values = aligned_bio["codec"].to_numpy()

    print(f"\nSSL eval rows:             {len(ssl_df):,}")
    print(f"Bio eval rows after prep:  {len(bio_df):,}")
    print(f"Aligned eval rows:         {len(aligned_bio):,}")

    if len(aligned_bio) != len(ssl_df):
        print(
            "\nWARNING: Some SSL eval rows did not align with Bio rows. "
            "This may happen if Bio feature extraction removed invalid/unvoiced files."
        )

    del ssl_df, bio_df, ssl_for_merge, bio_for_merge, aligned_bio, ssl_aligned
    gc.collect()

    return X_ssl_eval, X_bio_eval, y_eval, codec_values, ssl_cols


# ============================================================
# 7. BOOTSTRAP TABLE CREATION
# ============================================================

def evaluate_bootstrap_condition(condition_name, labels, ssl_scores, bio_scores, ssl_weight):
    fusion_scores = fuse_scores(ssl_scores, bio_scores, ssl_weight)

    rows = []

    for model_name, scores in [
        ("SSL-only", ssl_scores),
        ("Bio-only", bio_scores),
        ("SSL-BioFusion", fusion_scores)
    ]:
        eer, threshold = calculate_eer(labels, scores)
        ci = bootstrap_eer_ci(
            labels,
            scores,
            n_bootstrap=N_BOOTSTRAP,
            confidence=95,
            random_state=RANDOM_STATE
        )

        rows.append({
            "Condition": condition_name,
            "Model": model_name,
            "Files": len(labels),
            "EER (%)": round(eer, 4),
            "Bootstrap Mean EER (%)": round(ci["eer_mean"], 4),
            "95% CI Lower": round(ci["eer_lower"], 4),
            "95% CI Upper": round(ci["eer_upper"], 4),
            "EER Threshold": round(threshold, 6),
            "Valid Bootstrap Resamples": ci["valid_resamples"]
        })

    return rows


# ============================================================
# 8. MAIN EXECUTION
# ============================================================

print("=" * 90)
print("FULLY STANDALONE BOOTSTRAP STATISTICAL SIGNIFICANCE ANALYSIS")
print("=" * 90)

required_files = [
    EVAL_SSL_CSV,
    EVAL_BIO_CSV,
    SSL_SCALER_PATH,
    SSL_WEIGHTS_PATH,
    BIO_SCALER_PATH,
    BIO_WEIGHTS_PATH
]

print("\nChecking required files...")
for path in required_files:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing file: {path}")
    print(f"FOUND: {path}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")

print("\nLoading saved scalers...")
ssl_scaler = joblib.load(SSL_SCALER_PATH)
bio_scaler = joblib.load(BIO_SCALER_PATH)

print("\nPreparing 2021 evaluation features...")
X_ssl_eval, X_bio_eval, eval_labels, codec_values, ssl_cols = load_2021_eval_features(
    ssl_scaler=ssl_scaler,
    bio_scaler=bio_scaler
)

print("\nLoading trained models...")
ssl_model = SSLModel(input_dim=len(ssl_cols)).to(device)
bio_model = BioModel(input_dim=len(BIO_COLS)).to(device)

ssl_model.load_state_dict(torch.load(SSL_WEIGHTS_PATH, map_location=device))
bio_model.load_state_dict(torch.load(BIO_WEIGHTS_PATH, map_location=device))

print("\nRunning inference...")
eval_ssl_scores, eval_bio_scores, eval_labels = run_inference(
    ssl_model=ssl_model,
    bio_model=bio_model,
    ssl_features=X_ssl_eval,
    bio_features=X_bio_eval,
    labels=eval_labels,
    device=device
)

print("\nComputing bootstrap confidence intervals...")

all_rows = []

all_rows.extend(
    evaluate_bootstrap_condition(
        "Overall",
        eval_labels,
        eval_ssl_scores,
        eval_bio_scores,
        SSL_WEIGHT
    )
)

clean_mask = codec_values == "nocodec"
compressed_mask = codec_values != "nocodec"

if np.any(clean_mask):
    all_rows.extend(
        evaluate_bootstrap_condition(
            "Clean / No Codec",
            eval_labels[clean_mask],
            eval_ssl_scores[clean_mask],
            eval_bio_scores[clean_mask],
            SSL_WEIGHT
        )
    )

if np.any(compressed_mask):
    all_rows.extend(
        evaluate_bootstrap_condition(
            "Compressed",
            eval_labels[compressed_mask],
            eval_ssl_scores[compressed_mask],
            eval_bio_scores[compressed_mask],
            SSL_WEIGHT
        )
    )

bootstrap_results_df = pd.DataFrame(all_rows)

print("\n" + "=" * 90)
print("BOOTSTRAP STATISTICAL SIGNIFICANCE ANALYSIS RESULTS")
print("=" * 90)
print(f"Bootstrap resamples: {N_BOOTSTRAP}")
print("Confidence interval: 95%")
print(f"Fusion weight: {SSL_WEIGHT:.3f} SSL / {1.0 - SSL_WEIGHT:.3f} Bio")

display(bootstrap_results_df)

# output_csv = os.path.join(BASE_DIR, "bootstrap_statistical_significance_results.csv")
# bootstrap_results_df.to_csv(output_csv, index=False)

# print(f"\nSaved results to:\n{output_csv}")

==========================================================================================
FULLY STANDALONE BOOTSTRAP STATISTICAL SIGNIFICANCE ANALYSIS
==========================================================================================

Checking required files...
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_ssl_features.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\eval_df_bio_academic.csv
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_scaler.pkl
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\ssl_mlp_weights.pt
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_scaler.pkl
FOUND: C:\Users\adith\Desktop\Projects\Audio Deepfake\bio_academic_mlp_weights.pt

Using device: cuda

Loading saved scalers...

Preparing 2021 evaluation features...

Loading 2021 SSL eval features...

Loading 2021 Bio eval features...

Applying biological feature engineering...
Alignment key: filename + codec
Duplicate handling: using occurrence index within key groups

Aligning SSL and Bio eval rows...

Scaling SSL features...
Scaling biological features...

SSL eval rows:             401,933
Bio eval rows after prep:  351,910
Aligned eval rows:         351,910

WARNING: Some SSL eval rows did not align with Bio rows. This may happen if Bio feature extraction removed invalid/unvoiced files.

Loading trained models...

Running inference...

Inference: 100%|██████████| 172/172 [00:26<00:00,  6.53it/s]

Computing bootstrap confidence intervals...

==========================================================================================
BOOTSTRAP STATISTICAL SIGNIFICANCE ANALYSIS RESULTS
==========================================================================================
Bootstrap resamples: 1000
Confidence interval: 95%
Fusion weight: 0.950 SSL / 0.050 Bio

,Condition,Model,Files,EER (%),Bootstrap Mean EER (%),95% CI Lower,95% CI Upper,EER Threshold,Valid Bootstrap Resamples
0,Overall,SSL-only,351910,20.3386,20.3305,19.9932,20.6916,0.003290,1000
1,Overall,Bio-only,351910,29.5892,29.5855,29.1614,30.0003,0.617120,1000
2,Overall,SSL-BioFusion,351910,18.8454,18.8356,18.4720,19.2185,0.045530,1000
3,Clean / No Codec,SSL-only,39132,18.9786,19.0309,17.8262,20.0640,0.003903,1000
4,Clean / No Codec,Bio-only,39132,28.9148,28.9239,27.5701,30.1273,0.655523,1000
5,Clean / No Codec,SSL-BioFusion,39132,16.8688,16.9603,15.8194,18.1487,0.046754,1000
6,Compressed,SSL-only,312778,20.4963,20.4964,20.1343,20.8824,0.003221,1000
7,Compressed,Bio-only,312778,29.6442,29.6333,29.2040,30.0290,0.611802,1000
8,Compressed,SSL-BioFusion,312778,19.0441,19.0582,18.6720,19.4799,0.045405,1000

Saved results to:
C:\Users\adith\Desktop\Projects\Audio Deepfake\bootstrap_statistical_significance_results.csv